# This CI Workflow was deployed and configured by WarpWing and Nate.
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: "14.x"
  REDIS_VERSION: "6"
  MONGODB_VERSION: "4.4"

jobs:
  es-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm ci

      - name: es-lint
        run: npm run lint

  ejs-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm ci

      - name: ejs-lint
        run: npm run lint:ejs

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm ci

      - name: prettier
        run: npm run prettier

  buildts:
    name: build ts
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm ci

      - name: build ts
        run: npm run ts

  buildscss:
    name: build scss
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm ci

      - name: build scss
        run: npm run scss

  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Start Redis ${{ env.REDIS_VERSION }}
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ env.REDIS_VERSION }}

      - name: Start MongoBongo ${{ env.MONGODB_VERSION }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ env.MONGODB_VERSION }}

      - name: Install node dependencies
        run: npm ci

      - name: Run NPM Build Process
        run: npm run build --if-present
